AWSTemplateFormatVersion: "2010-09-09"
Description: A template to create an S3 bucket for static website hosting with a custom bucket name and public access.

Parameters:
  StackName:
    Type: String
    Description: Enter the stack name to be prefixed to bucket name.
    Default: some-random-stack-name-1234

Resources:
  MyWebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${StackName}-bucket-${AWS::AccountId}
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        IgnorePublicAcls: false
        BlockPublicPolicy: false
        RestrictPublicBuckets: false
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerPreferred

  MyBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref MyWebsiteBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: "*"
            Action: "s3:GetObject"
            Resource: !Sub ${MyWebsiteBucket.Arn}/*

Outputs:
  WebsiteURL:
    Value: !GetAtt MyWebsiteBucket.WebsiteURL
    Description: URL of the S3 bucket to host the website.
  BucketName:
    Value: !Ref MyWebsiteBucket
    Description: Name of the S3 bucket.
